<a href="https://colab.research.google.com/github/Koshi1321/Linear-Algebra_2nd-Sem/blob/main/Assignment_3FINAAAAAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 2: Matrices

# Objectives
At the end of this activity you will be able to:

Be familiar with matrices and their relation to linear equations.
Perform basic matrix operations.
Program and translate matrix equations and operations using Python.

# Discussion

In [64]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Matrices 
#### The notation and use of matrices is probably one of the fundanmentals of modern computing. Matrices are also handy representation of complex equations or multiple complex equations or multiple inter-related equations from 2- dimensional equations to even hundreds and thousans of them. It is a rectangular arrays of numbers, symbols, or expressions, arranged in rows and columns.

### Let's say for example you have A and B as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        4x -3y -z \\
        -3x + 5y +5z
    \end{array}
\right. \\
C= \left\{
    \begin{array}\
        w-x+y+z \\ 
        3w-6x -2y -6z \\
        6w-5x + 7y +5z
    \end{array}
\right. $$


### We could see that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 4 & -3 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 1 & 1 & 1 & 1 \\ 3 & -6 & -2 & -6 \\ 6 & -5 & 7 & 5\end{bmatrix}
$$


# Declaring Matrices
#### The set of numbers arranged in rows and columnsare called the elements, or entries, of the matrix. Denoted by i is the number of rows in the matrix while j stands  for the number of columns.
#### This can be represented just like the equation below.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [65]:
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [66]:
## Declaring a 2 x 2 matirx
A = np.array([
  [1, 3],
  [4, 5]
])
describe_mat(A)

Matrix:
[[1 3]
 [4 5]]

Shape:	(2, 2)
Rank:	2



In [67]:
G = np.array([
 [1,1,1],
 [2,3,4]
])
describe_mat(G)

Matrix:
[[1 1 1]
 [2 3 4]]

Shape:	(2, 3)
Rank:	2



In [68]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## According to shape

### Row and Column Matrices

#### Row and column matrices are common in vector and matrix computations. The horizontal entries are called rows while the vertical lines of entries are called columns.

In [69]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1,5,2,-8                
])
row_mat_2D = np.array([
  [1,3,5,10]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 1  5  2 -8]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  3  5 10]]

Shape:	(1, 4)
Rank:	2



In [70]:
## Declaring a Column Matrix

col_mat = np.array([
    [200000],
    [355],
    [55],
])
describe_mat(col_mat)

Matrix:
[[200000]
 [   355]
 [    55]]

Shape:	(3, 1)
Rank:	2



### Square Matrices
#### It is a matrix with the same sizes of rows and columns.

In [71]:
def describe_mat(matrix):
    is_square = True  if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n[matrix]\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nis Square: {is_square}\n')

In [72]:
square_mat = np.array([
  [1,4,7],
  [5,3,7],
  [1,7,5]
])

non_square_mat =  np.array([
  [8,9,10],
  [5,6,5]   
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[matrix]

Shape:	(3, 3)
Rank:	2
is Square: True

Matrix:
[matrix]

Shape:	(2, 3)
Rank:	2
is Square: False



# According to element values




## Null Matrix
### Null Matrix is a matrix having zero as each of its elements. 

In [73]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nis Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [74]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix
### Matrix in which all elements are zero.

In [75]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix
### Matrix in which all elements are 1s instead of 0s

In [76]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrix
### Square matrix in which all off-diagonal entries are zero

In [77]:
np.array([
   [7,0,0],
   [0,4,0],
   [0,0,6]      
])

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [78]:
d = np.diag([9,4,6,5])
d.shape[0] == d.shape[1]
d

array([[9, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 5]])

##Identity Matrix
### Square matrix having 1s diagonally and 0s everywhere else

In [79]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix
### matrix having zero in all elements below the main diagonal

In [81]:
np.array([
   [7,3,8,5],
   [0,4,9,-1],
   [0,0,6,2], 
   [0,0,0,2]     
])

array([[ 7,  3,  8,  5],
       [ 0,  4,  9, -1],
       [ 0,  0,  6,  2],
       [ 0,  0,  0,  2]])

## Lower Triangular Matrix
#### A lower triangular matrix is a matrix that has no values above the diagonal

In [82]:
np.array([
   [6,3,0,0],
   [9,4,5,0],
   [1,8,6,2]     
])

array([[6, 3, 0, 0],
       [9, 4, 5, 0],
       [1, 8, 6, 2]])

## Practice

#### 1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


### 2.Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


### 3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown




In [83]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


## 4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations


In [84]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra

####Addition

In [85]:
A = np.array([
     [9,3], 
     [5,4],
     [6,9]       
])
B = np.array([
     [1,2], 
     [1,2],
     [1,2]
])
A+B 

array([[10,  5],
       [ 6,  6],
       [ 7, 11]])

In [86]:
2+A 

array([[11,  5],
       [ 7,  6],
       [ 8, 11]])

### Subtraction

In [87]:
A = np.array([
     [9,3], 
     [5,4],
     [6,9]       
])
B = np.array([
     [1,2], 
     [1,2],
     [1,2]
])
A-B 

array([[8, 1],
       [4, 2],
       [5, 7]])

In [88]:
3-B

array([[2, 1],
       [2, 1],
       [2, 1]])

# Element-wise Multiplication

In [89]:
A*B
np.multiply(A,B)

array([[ 9,  6],
       [ 5,  8],
       [ 6, 18]])

In [90]:
2*A

array([[18,  6],
       [10,  8],
       [12, 18]])

#ACTIVITY 1

In [91]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [92]:
def mat_desc(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n\nSize:\t{matrix.size}\n')

In [93]:
A = np.array ([
    [1, 2,5,7],
    [3, 1,6,2],
    [5, 8,3,1] 
])
mat_desc(A)

Matrix:
[[1 2 5 7]
 [3 1 6 2]
 [5 8 3 1]]

Shape:	(3, 4)
Rank:	2

Size:	12



In [94]:
B = np.array ([
    [9, 5,6,10],
    [2, 9,4,6],
    [6, 7,5,4],
    [5, 8, 3, 1]
])
mat_desc(B)

Matrix:
[[ 9  5  6 10]
 [ 2  9  4  6]
 [ 6  7  5  4]
 [ 5  8  3  1]]

Shape:	(4, 4)
Rank:	2

Size:	16



In [95]:
C = np.array([
    [8, 2,4,6,3],
    [9, 4,3,5,6],
    [1, 5,3,9,7],
    [1, 9,8,1,5],
    [9, 4,3,5,6]
])
mat_desc(C)

Matrix:
[[8 2 4 6 3]
 [9 4 3 5 6]
 [1 5 3 9 7]
 [1 9 8 1 5]
 [9 4 3 5 6]]

Shape:	(5, 5)
Rank:	2

Size:	25



In [96]:
def mat_desc(matrix):
   if(matrix.shape[0] == matrix.shape[1]):
     square =True
     print('Matrix is square')
   else:
     print('Matrix is non square')

In [97]:
sqr = np.array([
    [6,5,7],
    [2,5,9],
    [2,4,8]
])

mat_desc(sqr)


Matrix is square


In [98]:
sqr = np.array([
    [1,2,5,1,5],
    [3,3,8,2,6],
    [2,4,8,6,8],
    [5,5,6,6,9],
    [9,7,4,6,2]

])
mat_desc(sqr)

Matrix is square


In [99]:
sqr = np.array([
    [1,2,5,1,5,9],
    [3,3,8,2,6,8],
    [2,4,8,6,8,3],
    [5,5,6,6,9,1],
    [9,7,4,6,2,9]

])
mat_desc(sqr)

Matrix is non square


In [100]:
def mat_desc(matrix):
  if(matrix.size > 0):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print('Matrix is not empty')
  else:
    print('Matrix is empty')

In [101]:
empty_mat = np.array([])
mat_desc(empty_mat)

Matrix is empty


In [102]:
empty_mat = np.array([
    [1,2,5,1,5,9],
    [3,3,8,2,6,8],
    [2,4,8,6,8,3],
    [5,5,6,6,9,1],
    [9,7,4,6,2,9]

])
mat_desc(empty_mat)

Matrix is not empty


In [103]:
empty_mat = np.array([
    [2,2,5,1,4,3],
    [3,9,6,2,8,9]

])
mat_desc(empty_mat)

Matrix is not empty


In [104]:
def mat_desc(matrix):
  zeros = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zeros == matrix).all()):
    print('Matrix is zero')
  else:
    print('Matrix is not zero')

In [105]:
zeros = np.array([
      [1,5,4],
      [1,2,3]
  
])
mat_desc(zeros)

Matrix is not zero


## Task 2

In [106]:
def mat_operations(matrix1, matrix2):
  matrix1 = np.array(matrix1)
  matrix2 = np.array(matrix2)
  print('Matrix 1 entries are:\n',matrix1)
  print('Matrix 2 entries are:\n', matrix2)
  if(matrix1.shape != matrix2.shape):
    print('A non-square matrix cannot perform an operation')
    return
  print('Sum:')
  summ=matrix1+matrix2
  print(summ)
  print('Difference:')
  diff= matrix1-matrix2
  print(diff)
  print('Element-wise multiplication:') 
  ewm = matrix1*matrix2
  print(ewm)
  print('Element-wise division:')
  ewd = matrix1/matrix2
  print(ewd)

In [107]:
mat_operations([
    [2,1,6,1,2,5], 
    [6,7,7,2,3,9],
    [3,3,9,6,7,4],
    [3,4,6,6,5,6]],

    [[1,2,2,3,9,3], 
    [1,2,2,1,1,4],
    [1,2,1,3,1,5],
    [3,6,9,6,7,6]]) 



Matrix 1 entries are:
 [[2 1 6 1 2 5]
 [6 7 7 2 3 9]
 [3 3 9 6 7 4]
 [3 4 6 6 5 6]]
Matrix 2 entries are:
 [[1 2 2 3 9 3]
 [1 2 2 1 1 4]
 [1 2 1 3 1 5]
 [3 6 9 6 7 6]]
Sum:
[[ 3  3  8  4 11  8]
 [ 7  9  9  3  4 13]
 [ 4  5 10  9  8  9]
 [ 6 10 15 12 12 12]]
Difference:
[[ 1 -1  4 -2 -7  2]
 [ 5  5  5  1  2  5]
 [ 2  1  8  3  6 -1]
 [ 0 -2 -3  0 -2  0]]
Element-wise multiplication:
[[ 2  2 12  3 18 15]
 [ 6 14 14  2  3 36]
 [ 3  6  9 18  7 20]
 [ 9 24 54 36 35 36]]
Element-wise division:
[[2.         0.5        3.         0.33333333 0.22222222 1.66666667]
 [6.         3.5        3.5        2.         3.         2.25      ]
 [3.         1.5        9.         2.         7.         0.8       ]
 [1.         0.66666667 0.66666667 1.         0.71428571 1.        ]]


In [108]:
mat_operations([
    [2,1,6], 
    [6,7,7],
    [3,3,9],
    [3,4,6]],

    [[1,2,2], 
    [1,2,2],
    [1,2,1],
    [3,6,9]]) 

Matrix 1 entries are:
 [[2 1 6]
 [6 7 7]
 [3 3 9]
 [3 4 6]]
Matrix 2 entries are:
 [[1 2 2]
 [1 2 2]
 [1 2 1]
 [3 6 9]]
Sum:
[[ 3  3  8]
 [ 7  9  9]
 [ 4  5 10]
 [ 6 10 15]]
Difference:
[[ 1 -1  4]
 [ 5  5  5]
 [ 2  1  8]
 [ 0 -2 -3]]
Element-wise multiplication:
[[ 2  2 12]
 [ 6 14 14]
 [ 3  6  9]
 [ 9 24 54]]
Element-wise division:
[[2.         0.5        3.        ]
 [6.         3.5        3.5       ]
 [3.         1.5        9.        ]
 [1.         0.66666667 0.66666667]]


In [109]:
mat_operations([
    [2,1,6,5], 
    [6,7,7,1],
    [3,3,9,3],
    [3,4,6,9]],

    [[1,2,2,2], 
    [1,2,2,4],
    [1,2,1,8],
    [3,6,9,5]]) 

Matrix 1 entries are:
 [[2 1 6 5]
 [6 7 7 1]
 [3 3 9 3]
 [3 4 6 9]]
Matrix 2 entries are:
 [[1 2 2 2]
 [1 2 2 4]
 [1 2 1 8]
 [3 6 9 5]]
Sum:
[[ 3  3  8  7]
 [ 7  9  9  5]
 [ 4  5 10 11]
 [ 6 10 15 14]]
Difference:
[[ 1 -1  4  3]
 [ 5  5  5 -3]
 [ 2  1  8 -5]
 [ 0 -2 -3  4]]
Element-wise multiplication:
[[ 2  2 12 10]
 [ 6 14 14  4]
 [ 3  6  9 24]
 [ 9 24 54 45]]
Element-wise division:
[[2.         0.5        3.         2.5       ]
 [6.         3.5        3.5        0.25      ]
 [3.         1.5        9.         0.375     ]
 [1.         0.66666667 0.66666667 1.8       ]]
