<a href="https://colab.research.google.com/github/Koshi1321/Linear-Algebra_2nd-Sem/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 2: Matrices

# Objectives
At the end of this activity 

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices 
### The notation and use of matrices is probably one of the fundanmentals of modern computing. Matrices are also handy representation of complex equations or multiple complex equations or multiple inter-related equations from 2- dimensional equations to even hundreds and thousans of them.

### Let's say for example you have A and B as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        4x -3y -z \\
        -3x + 5y +5z
    \end{array}
\right. \\
C= \left\{
    \begin{array}\
        w-x+y+z \\ 
        3w-6x -2y -6z \\
        6w-5x + 7y +5z
    \end{array}
\right. $$


### We could see that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 4 & -3 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 1 & 1 & 1 & 1 \\ 3 & -6 & -2 & -6 \\ 6 & -5 & 7 & 5\end{bmatrix}
$$


# Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [15]:
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [16]:
## Declaring a 2 x 2 matirx
A = np.array([
  [1, 3],
  [4, 5]
])
describe_mat(A)

Matrix:
[[1 3]
 [4 5]]

Shape:	(2, 2)
Rank:	2



In [18]:
G = np.array([
 [1,1,1],
 [2,3,4]
])
describe_mat(G)

Matrix:
[[1 1 1]
 [2 3 4]]

Shape:	(2, 3)
Rank:	2



In [21]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## According to shape

## Row and Column Matrices

#### Row and column matrices are common in vector and matrix computations.

In [28]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1,5,2,-8                
])
row_mat_2D = np.array([
  [1,3,5,10]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 1  5  2 -8]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  3  5 10]]

Shape:	(1, 4)
Rank:	2



In [31]:
## Declaring a Column Matrix

col_mat = np.array([
    [200000],
    [355],
    [55],
])
describe_mat(col_mat)

Matrix:
[[200000]
 [   355]
 [    55]]

Shape:	(3, 1)
Rank:	2



## Square Matrices
### desc

In [34]:
def describe_mat(matrix):
    is_square = True  if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n[matrix]\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nis Square: {is_square}\n')

In [38]:
square_mat = np.array([
  [1,4,7],
  [5,3,7],
  [1,7,5]
])

non_square_mat =  np.array([
  [8,9,10],
  [5,6,5]   
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[matrix]

Shape:	(3, 3)
Rank:	2
is Square: True

Matrix:
[matrix]

Shape:	(2, 3)
Rank:	2
is Square: False



### According to element values

In [41]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nis Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [43]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

In [47]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix

In [49]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrix

In [55]:
np.array([
   [7,0,0],
   [0,4,0],
   [0,0,6]      
])

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [54]:
d = np.diag([9,4,6,5])
d.shape[0] == d.shape[1]
d

array([[9, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 5]])

##Identity Matrix

In [56]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

##Upper Triangular Matrix

In [63]:
np.array([
   [7,0,0,5],
   [0,4,0,-1],
   [0,0,6,2], 
   [0,9,5,2]     
])

array([[ 7,  0,  0,  5],
       [ 0,  4,  0, -1],
       [ 0,  0,  6,  2],
       [ 0,  9,  5,  2]])

## Lower Triangular Matrix
#### A lower triangular matrix is a matrix that has no values above the diagonal

In [59]:
np.array([
   [6,3,0,4],
   [0,4,5,-1],
   [1,0,6,2]     
])

array([[ 6,  3,  0,  4],
       [ 0,  4,  5, -1],
       [ 1,  0,  6,  2]])

## Practice

#### 1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


### 2.Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


### 3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown




In [64]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


## 4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations


In [65]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra

####Addition

In [66]:
A = np.array([
     [9,3], 
     [5,4],
     [6,9]       
])
B = np.array([
     [1,2], 
     [1,2],
     [1,2]
])
A+B 

array([[10,  5],
       [ 6,  6],
       [ 7, 11]])

In [67]:
2+A 

array([[11,  5],
       [ 7,  6],
       [ 8, 11]])

### Subtraction

In [68]:
A = np.array([
     [9,3], 
     [5,4],
     [6,9]       
])
B = np.array([
     [1,2], 
     [1,2],
     [1,2]
])
A-B 

array([[8, 1],
       [4, 2],
       [5, 7]])

In [69]:
3-B

array([[2, 1],
       [2, 1],
       [2, 1]])

# Element-wise Multiplication

In [70]:
A*B
np.multiply(A,B)

array([[ 9,  6],
       [ 5,  8],
       [ 6, 18]])

In [71]:
2*A

array([[18,  6],
       [10,  8],
       [12, 18]])