<a href="https://colab.research.google.com/github/Koshi1321/Linear-Algebra_2nd-Sem/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra for ChE

### Laboratory 6: Matrix Operations

###Discussion

In [267]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


### Transposition

####One of the fundamental operations in matrix algebra is transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [268]:
A = np.array ([
    [9,-1,0],
    [3,7,5]
])

In [269]:
AT1 = np.transpose(A)
AT1

array([[ 9,  3],
       [-1,  7],
       [ 0,  5]])

In [270]:
AT2 = A.T
AT2

array([[ 9,  3],
       [-1,  7],
       [ 0,  5]])

In [271]:
np.array_equiv(AT1,AT2)

True

In [272]:
B = np.array([
    [5,6,1,1],
    [7,6,5,3],
])
B.shape

(2, 4)

In [273]:
np.transpose(B).shape

(4, 2)

In [274]:
B.T.shape

(4, 2)

###Dot Product

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.

In [275]:
X = np.array([
    [9,5],
    [6,4],
    [1,7]
])
Y = np.array([
    [-9,8,1],
    [3,4,5]
])

In [276]:
np.array_equiv(X,Y)

False

In [277]:
np.dot(X,Y)

array([[-66,  92,  34],
       [-42,  64,  26],
       [ 12,  36,  36]])

In [278]:
X.dot(Y)

array([[-66,  92,  34],
       [-42,  64,  26],
       [ 12,  36,  36]])

In [279]:
X @ Y

array([[-66,  92,  34],
       [-42,  64,  26],
       [ 12,  36,  36]])

In [280]:
np.matmul(X,Y)

array([[-66,  92,  34],
       [-42,  64,  26],
       [ 12,  36,  36]])

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [281]:
A = np.array([
    [8, 4,6],
    [5,-2,5],
    [0, 1,1],
    [0, 8,6]
])
B = np.array([
    [3, 6,1],
    [9,7,-9],
    [1, 6,7],
    [6, 7,4]
])
C = np.array([
    [0,9,7],
    [2,7,6],
    [7,5,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(4, 3)
(4, 3)
(3, 3)


In [282]:
A @ C

array([[ 50, 130,  92],
       [ 31,  56,  33],
       [  9,  12,   8],
       [ 58,  86,  60]])

In [283]:
B @ C

array([[ 19,  74,  59],
       [-49,  85,  87],
       [ 61,  86,  57],
       [ 42, 123,  92]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [284]:
A @ B.T

array([[ 54,  46,  74, 100],
       [  8, -14,  28,  36],
       [  7,  -2,  13,  11],
       [ 54,   2,  90,  80]])

In [285]:
X = np.array([
    [8,1,6,1]
])
Y = np.array([
    [7,9,5,-5]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [286]:
Y.T @ X

array([[ 56,   7,  42,   7],
       [ 72,   9,  54,   9],
       [ 40,   5,  30,   5],
       [-40,  -5, -30,  -5]])

## Rule 2: Dot Product has special properties
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$


In [287]:
A = np.array([
    [7,5,4],
    [3,4,9],
    [5,1,7]
])
B = np.array([
    [9,6,7],
    [3,7,1],
    [9,5,7]
])
C = np.array([
    [2,9,8],
    [3,4,0],
    [2,5,6]
])

In [288]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [289]:
v_mat = np.zeros(A.shape)
v_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [290]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [291]:
np.array_equal(a_dot_z,v_mat)

True

In [292]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [293]:
A@B

array([[114,  97,  82],
       [120,  91,  88],
       [111,  72,  85]])

In [294]:
B@A

array([[116,  76, 139],
       [ 47,  44,  82],
       [113,  72, 130]])

In [295]:
np.array_equiv(A@B, B@A)

False

In [296]:
A@(B@C)

array([[ 683, 1824, 1404],
       [ 689, 1884, 1488],
       [ 608, 1712, 1398]])

In [297]:
(A@B)@C

array([[ 683, 1824, 1404],
       [ 689, 1884, 1488],
       [ 608, 1712, 1398]])

In [298]:
np.array_equiv(A@(B@C),(A@B)@C)

True

In [299]:
A@(B+C)

array([[151, 200, 162],
       [156, 179, 166],
       [138, 156, 167]])

In [300]:
A@B+A@C

array([[151, 200, 162],
       [156, 179, 166],
       [138, 156, 167]])

In [301]:
np.array_equiv(A@(B+C),A@B+A@C)

True

In [302]:
(B+C)@A

array([[197, 130, 284],
       [ 80,  75, 130],
       [172, 108, 225]])

In [303]:
B@A+C@A

array([[197, 130, 284],
       [ 80,  75, 130],
       [172, 108, 225]])

In [304]:
np.array_equiv((B+C)@A,B@A+C@A)

True

In [305]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [306]:
A@I

array([[7., 5., 4.],
       [3., 4., 9.],
       [5., 1., 7.]])

In [307]:
A

array([[7, 5, 4],
       [3, 4, 9],
       [5, 1, 7]])

In [308]:
np.array_equiv(A@I, A)

True

In [341]:
V=np.zeros(A.shape)
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [342]:
A@V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [343]:
np.array_equiv(A@V, V)

True

### Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [310]:
A = np.array([
    [9,2],
    [5,6]
])
np.linalg.det(A)

44.000000000000014

In [311]:
B = np.array([
    [9,4,4],
    [6,7,5],
    [8,6,5]
])
np.linalg.det(B)

5.000000000000019

In [312]:
C= np.array([
              [9,7,4,6],
              [3,6,5,1],
              [0,7,9,-3],
              [21,4,6,-5]
])
np.linalg.det(C)

-1151.9999999999993

### Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [313]:
M = np.array([
    [9,4],
    [-5, 7]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[0, 0],
       [0, 1]])

In [314]:
P = np.array([
              [9,1,5],
              [-2,-8,-1],
              [2,6,-9]
])
Q = np.linalg.inv(P)
Q

array([[ 0.11111111,  0.05555556,  0.05555556],
       [-0.02849003, -0.12962963, -0.0014245 ],
       [ 0.00569801, -0.07407407, -0.0997151 ]])

In [315]:
Q@P

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [ 6.50521303e-18,  1.00000000e+00, -1.51788304e-18],
       [ 2.77555756e-17,  8.32667268e-17,  1.00000000e+00]])

In [316]:
N = np.array([
    [6,2,1,6,1,5,1],
    [2,8,5,3,6,5,4],
    [1,3,0,5,1,3,4],
    [3,2,2,6,5,3,2],
    [5,1,2,0,2,2,6],
    [6,-11,2,1,3,2,-5],
    [-2,-6,5,3,2,10,10],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

### TASK 1

In [317]:
A = np.array([
    [9,8,1,5],
    [1,6,5,3],
    [6,8,7,0],
    [7,4,1,8]
])
B = np.array([
    [8,1,6,1],
    [-4,5,-5,7],
    [-2,6,3,3],
    [7,4,1,6]
])
C = np.array([
    [7,-5,4,3],
    [6,5,1,5],
    [4,7,2,9],
    [1,3,1,7]
])

In [318]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [319]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [320]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [321]:
np.array_equal(a_dot_z,z_mat)

True

In [322]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


True

In [323]:
A@B

array([[73, 75, 22, 98],
       [-5, 73, -6, 76],
       [ 2, 88, 17, 83],
       [94, 65, 33, 86]])

In [324]:
B@A

array([[116, 122,  56,  51],
       [-12, -14,  -7,  51],
       [ 27,  56,  52,  32],
       [115, 112,  40,  95]])

In [325]:
np.array_equiv(A@B, B@A)

False

In [326]:
A@(B@C)

array([[1147,  458,  509, 1478],
       [ 455,  576,  117,  828],
       [ 693,  798,  213, 1180],
       [1266,  344,  593, 1506]])

In [327]:
(A@B)@C

array([[1147,  458,  509, 1478],
       [ 455,  576,  117,  828],
       [ 693,  798,  213, 1180],
       [1266,  344,  593, 1506]])

In [328]:
np.array_equiv(A@(B@C),(A@B)@C)

True

In [329]:
A@(B+C)

array([[193,  92,  73, 209],
       [ 61, 142,  17, 175],
       [120, 147,  63, 204],
       [179,  81,  75, 192]])

In [330]:
A@B+A@C

array([[193,  92,  73, 209],
       [ 61, 142,  17, 175],
       [120, 147,  63, 204],
       [179,  81,  75, 192]])

In [331]:
(B+C)@A

array([[219, 192,  69,  95],
       [ 88,  92,  36, 136],
       [145, 182, 114, 145],
       [182, 174,  70, 165]])

In [332]:
B@A+C@A

array([[219, 192,  69,  95],
       [ 88,  92,  36, 136],
       [145, 182, 114, 145],
       [182, 174,  70, 165]])

In [333]:
np.array_equiv((B+C)@A,B@A+C@A)

True

In [334]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [335]:
A@I

array([[9., 8., 1., 5.],
       [1., 6., 5., 3.],
       [6., 8., 7., 0.],
       [7., 4., 1., 8.]])

In [336]:
A

array([[9, 8, 1, 5],
       [1, 6, 5, 3],
       [6, 8, 7, 0],
       [7, 4, 1, 8]])

In [337]:

np.array_equiv(A@I, A)

True

In [338]:
V=np.zeros(A.shape)
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [339]:
A@V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [340]:
np.array_equiv(A@V, V)

True